### ISSUE TITLE
Binary formats

### ISSUE THREAD

**Issue by AllWize** [AllWize/allwize#1]
Right now we are using strings payloads in the examples (easy to parse, human friendly,...). But we will need a way to pack messages in a binary way (more efficient from the size point of view).

It might be interesting to provide a way to do it from the library itself. Maybe inspired by the `pack` method in python (known format) or the Lua `pack` (http://lua-users.org/wiki/LuaPack).

**Comment by Allwize** [comment]
There is a MBus specification based on DIF and VIF fields.

**Comment by xoseperez** [comment]
The `slave_allwize_k2_lpp` and `slave_allwize_k2_mbus` examples show how to use binary encoded payloads with the AllWize library. Check the [MQTT Bridge page in the AllWize wiki](http://wiki.allwize.io/index.php?title=MQTT_Bridge) to know more about these formats and how to decode them.
